---
title: "Street Functional Classification"
author: "Carole Voulgaris"
date: "2/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(leaflet)
library(tidyverse)
library(sf)
library(here)
library(RColorBrewer)
library(htmlwidgets)
```

## Load data

```{r}
streets <- here("big_files",
                "Streets",
                "Streets.shp") %>%
  st_read() %>%
  st_transform("WGS84")
```

## Map data

```{r}
my_pal <- colorFactor(brewer.pal(7, "Set1"), 
                      domain = streets$FuncClass)

map <- leaflet(streets) %>%
  addProviderTiles(provider = "Stamen.TonerLite") %>%
  addPolylines(weight = 2.5,
               color = ~my_pal(FuncClass),
               popup = ~FuncClass,
               opacity = 1) %>%
    addLegend("bottomright", 
              pal = my_pal, 
              values = ~FuncClass,
              title = "Functional Classification",
              opacity = 1) %>%
  addLegend("bottomleft",
            title = "Data source",
            colors = "white",
            labels = "https://data.somervillema.gov/")

saveWidget(map, "functional-class.html")
```

